dataset:
  annotations_path: train_val # path for the annotations data
  shift: None # shifts of the dataset
  workers: 4 # number of workers for the dataloader
  stride: 2 # stride in case of dense sampling
  resolution: 224 # input resolution to the model
  RGB:
    data_path: '../action_net/frames/ActionNet_S04/' # path to RGB data
    tmpl: "img_{:010d}.jpg" # format of RGB filenames
    features_name: test_feat_actionnet
  Event: # not neeeded for the project
    rgb4e: 6